# Generated by Django 5.2.7 on 2025-10-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.RemoveField(
            model_name="channel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="description",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="title",
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.CharField(max_length=100),
        ),
    ]
