# Generated by Django 5.2.7 on 2025-10-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_options_remove_channel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("timestamp",)},
        ),
        migrations.RenameField(
            model_name="message",
            old_name="created_at",
            new_name="timestamp",
        ),
    ]
