# Generated by Django 5.2.7 on 2025-10-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Audio file URL'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('mixed', 'Mixed Content')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image file URL'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(help_text='Text content or description'),
        ),
    ]
